export const PRODUCTS_DATA = [
  {
    id: "prd-9823id42tgfh12",
    title: "Classic Cotton Shirt",
    price: 45000,
    desc: "A breathable, high-quality cotton shirt suitable for formal and casual wear.",
    thumbnail_url: "",
    rating: 4.5,
    category: "men",
    review_count: 82,
  },
  {
    id: "prd-1122id88tgfh99",
    title: "Urban Street Hoodie",
    price: 55000,
    desc: "Comfortable oversized hoodie with a minimalist design.",
    thumbnail_url: "",
    rating: 4.7,
    category: "unisex",
    review_count: 215,
  },
  {
    id: "prd-5544id11tgfh00",
    title: "Leather Crossbody Bag",
    price: 120000,
    desc: "Handcrafted genuine leather bag with gold-toned hardware.",
    thumbnail_url: "",
    rating: 4.9,
    category: "accessories",
    review_count: 45,
  },
  {
    id: "prd-57935729egf2",
    title: "Special Laptop Bag",
    price: 120000,
    desc: "Handcrafted genuine leather bag with gold-toned hardware.",
    thumbnail_url: "",
    rating: 4.2,
    category: "accessories",
    review_count: 15,
  },
  {
    id: "prd-fo2it2nfieoewf",
    title: "Pure Cotton Cardigan",
    price: 120000,
    desc: "Handcrafted genuine leather bag with gold-toned hardware.",
    thumbnail_url: "",
    rating: 4.1,
    category: "unisex",
    review_count: 145,
  },
];
